<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto

namespace GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xF2\x01\x0A\x0Dservice.proto\x12\x05proto\"r\x0A\x07Request\x12*\x0A\x06header\x18\x01 \x03(\x0B2\x1A.proto.Request.HeaderEntry\x12\x0C\x0A\x04body\x18\x02 \x01(\x0C\x1A-\x0A\x0BHeaderEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x09:\x028\x01\"\x1C\x0A\x08Response\x12\x10\x0A\x08response\x18\x01 \x01(\x0C24\x0A\x07Service\x12)\x0A\x04Call\x12\x0E.proto.Request\x1A\x0F.proto.Response\"\x00B\x0AZ\x08../go/pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

